spring:
  application:
    name: order
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangFrame/configRepository
          username: liangFrame
          password: baobao19950802
env:
  test
