spring: 
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    enabled: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    check-template: true
    check-template-location: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    druid: ## 当前2.1.3版本搭配的mybatis和Druid的网址：https://blog.csdn.net/weixin_41813035/article/details/87895865#commentBox
      initial-size: 100  # 初始化大小
      min-idle: 100  # 最小
      max-active: 1000  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: SELECT 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    timeout: 100000 #连接超时时间 （毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10 # 消费者数量
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0D
  #MyBatis配置
mybatis:
  #  mapper-locations: classpath:mapper/**/*.xml   #配置Mapper.xml文件所在路径
  type-aliases-package: cn.lframe.seckill.domain #配置别名
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 5000
go:
  name: 90
